### ISSUE TITLE
Detect code review category based on GitHub url

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/browser-wakatime#187]
When the url matches regex `github.com/[^/]+/[^/]+/pull/\d+/files` let's add heartbeat json payload attribute:

```json
{
  …
  "category": "code reviewing",
  …
}
```

**Comment by LaoshuBaby** [comment]
Oh looks my #249 are similar to this issue^

By the way, if wakatime allow customed regex, I guess I can just add `readthedocs.io` for once, and don't need to add it for different project.

---

Regex feature was first requested in #25
