### ISSUE TITLE
Close the options window after clicking Save

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/browser-wakatime#202]
Currently there's no indication that the settings are saved after clicking `Save` button. We should close the options window after successfully saving the extension options, and for bonus show some kind of toast saying they were saved if possible.

**Comment by jvelezpo** [comment]
The toast will be part of the upgrade bootstrap to v5 [PR](https://github.com/wakatime/browser-wakatime/pull/158)

**Comment by PaoloJr90** [comment]
Hello! Just adding here that clicking `Save` in both the Chrome and Firefox browser extensions does not indicate that the `Options` were saved; it appears to be frozen (side-bar scroll indicator does show some movement)
Here is an image for reference:
![Screenshot 2023-07-31 122248](https://github.com/wakatime/browser-wakatime/assets/57420955/2177c7b4-1542-4c70-ba27-da6741c08260)
