### ISSUE TITLE
Allow to request permissions for custom hosts

### ISSUE THREAD

**Issue by muety** [wakatime/browser-wakatime#209]
#130 introduced the ability to configure custom API URLs, so the plugin can be used with self-hosted WakaTime alternative like [Wakapi](https://github.com/muety/wakapi) as well. However, to actually use this, people would have to build their own version of the browser add-on with `host_permissions` configured to permit requests to their own instances.

I propose to ...
* ... allow `wakapi.dev` by default.
* ... to request for optional host permissions when custom URL is configured (see [here](https://stackoverflow.com/questions/71913706/is-it-possible-for-a-webextension-addon-to-request-permission-for-a-specific-web), [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/permissions/request#examples) and [here](https://github.com/SettingDust/obsidian-web-clipper/blob/main/src/manifest.json)).

**Comment by muety** [comment]
What do you think, @alanhamlett? Would you be accepting a PR for this?

**Comment by alanhamlett** [comment]
Yes, sounds good.

**Comment by alanhamlett** [comment]
I don't want to allow wakapi.dev by default, but we should lazy-request permissions when any custom api url is used.

**Comment by varac** [comment]
@alanhamlett  Could you please release a new version containing this change to fully support self-hosted backends ? Thanks !

**Comment by alanhamlett** [comment]
@jvelezpo manages Chrome and Firefox releases, he can get a new version released.

**Comment by jvelezpo** [comment]
I will cut a release today

**Comment by jvelezpo** [comment]
@varac @alanhamlett the newest version is relaesed alredy to FF and chrome

**FF** 
```
Last Updated: July 17, 2023
    Status:[ Approved ](https://addons.mozilla.org/en-US/developers/addon/wakatimes/versions)
    Listed Version: [3.0.17](https://addons.mozilla.org/en-US/firefox/addon/wakatimes/versions/)
```

**Chrome**
Version: 3.0.17
Last updated Jul 13, 2023
Status Published - public

**Comment by varac** [comment]
Sorry for that - I now see the proper wakapi  API endpoint, with this it works ! Thanks !
