### ISSUE TITLE
Canva for Chrome extension 

### ISSUE THREAD

**Issue by WakaCarlos** [wakatime/browser-wakatime#211]
Hi,

I noticed while using Canva that the chrome extension does not label it as "designing" in WakaTime Dashboard anymore.
Would be great to if it could be fixed.
Thank you :)
Carlos

![Screen](https://github.com/wakatime/browser-wakatime/assets/133266972/71cca0a5-331f-4c9b-bd6e-43d8ba3458d6)

**Comment by alanhamlett** [comment]
Can you check if it's fixed in v3.0.18?

**Comment by alanhamlett** [comment]
It's not working because of bug #229.

**Comment by jvelezpo** [comment]
V3.0.19 should fix this
Will be released as soon as we merge this one https://github.com/wakatime/browser-wakatime/pull/230 😎

**Comment by alanhamlett** [comment]
Fixed in latest release.
