### ISSUE TITLE
Typo in WakaTimeCore.ts L259

### ISSUE THREAD

**Issue by toptalo** [wakatime/browser-wakatime#215]
I think there are typo

https://github.com/wakatime/browser-wakatime/blob/c4029f5fee62e69c68fa6731cc5dc4d1c30a07b2/src/core/WakaTimeCore.ts#L259
Should be 
```javascript
const lineRe = new RegExp(cleanLine.replace('.', '\\.').replace('*', '.*')); 
```

**Comment by toptalo** [comment]
Also on line 264
https://github.com/wakatime/browser-wakatime/blob/c4029f5fee62e69c68fa6731cc5dc4d1c30a07b2/src/core/WakaTimeCore.ts#L264

I think should be `projectName` instead of `null`

**Comment by toptalo** [comment]
Why i am here:

I want to track my activity in google chats
URL looks like `https://mail.google.com/chat/u/1/?zx=XXXXXXXXX#chat/space/AAAAxxXXXXX`
zx search param can be suddenly changed.
space is ID of chat
So I have add asterisk in place of changeable part of URL to my whitelist, like so:
`https://mail.google.com/chat/u/1/*/space/AAAAxxXXXXX@@projectName`

But in WakaTime Icon I see `This URL is not in your whitelist`

**Comment by alanhamlett** [comment]
Fixed in latest version.
