### ISSUE TITLE
Microsoft Edge support?

### ISSUE THREAD

**Issue by T0kyoB0y** [wakatime/browser-wakatime#220]
It would be cool if the extension were also available for Edge.

**Comment by alanhamlett** [comment]
@jvelezpo I think it does work for Edge, or not yet?

**Comment by T0kyoB0y** [comment]
Oh, I'm sorry, I just realized something. However, when I use the extension on Edge, the Wakatime dashboard shows that I've been using Chrome instead of Edge. It may sound silly, but I would really appreciate it if it accurately reflected that I'm using Edge rather than Chrome on the Wakatime dashboard.

![image](https://github.com/wakatime/browser-wakatime/assets/119447307/2513bc3d-b5a0-4294-b6ae-7a4a50767d3b)

**Comment by alanhamlett** [comment]
The extension defaults to `Chrome` here:
https://github.com/wakatime/browser-wakatime/blob/89a93e2c0a1cbf0860c00efe1f5a4681a6337857/src/core/WakaTimeCore.ts#L338

I'll fix that by detecting Edge browser.

**Comment by alanhamlett** [comment]
Fixed with 519dcb31b7666cce98c2fa059c5bc69c7713599d.

**Comment by alanhamlett** [comment]
@jvelezpo when can we release the new version with this fix?

**Comment by T0kyoB0y** [comment]
thx

**Comment by alanhamlett** [comment]
The WakaTime extension is now available in the Microsoft Edge store:
https://microsoftedge.microsoft.com/addons/detail/wakatime/cdnpfnaadjmaplhghnlonephmabegadl
