### ISSUE TITLE
Support Microsoft Edge browser

### ISSUE THREAD

**Issue by erruicoders** [wakatime/browser-wakatime#227]
I hope the author can add support for the Microsoft Edge browser plugin

**Comment by alanhamlett** [comment]
The WakaTime extension is now available in the Microsoft Edge store:
https://microsoftedge.microsoft.com/addons/detail/wakatime/cdnpfnaadjmaplhghnlonephmabegadl

**Comment by alanhamlett** [comment]
Wakapi is a separate project, you need to open an issue over there.

**Comment by erruicoders** [comment]
> Wakapi is a separate project, you need to open an issue over there.

OK, a new Issue has been submitted in the Wakapi repository
