### ISSUE TITLE
Page script should not try executing service worker code

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/browser-wakatime#229]
https://github.com/wakatime/browser-wakatime/blob/7d4fb6b90f3092421d37ff9947db077a73bcc746/src/wakatimeScript.ts#L60

The page script needs to post a message to the service worker instead of directly calling code meant to only run in the background with access to the Chrome extension api.

To fix this, send a message to the service worker with the current page's `DesignProject` info as JSON. Listen for that message in the service worker, save the `DesignProject` data and re-use it for all future heartbeats sent for the current tab.

**Comment by jvelezpo** [comment]
https://github.com/wakatime/browser-wakatime/pull/230
