### ISSUE TITLE
Fix logging type `entire url`

### ISSUE THREAD

**Issue by jvelezpo** [wakatime/browser-wakatime#235]
I got this email from **Eduard Breitenbach**
Tested this on latest version on looks like when logging type is set to `entire url` is not sending the correct value to the BE
```
Hello wakatime-Team,

I would really need the entire URLs from the chrome extension for whitelisted domains. 

I’ve set the logging type to „Entire URL“ in the options of the extension, but unfortunately it doesn’t work for me. How can I fix it?
 
Thank you!!


Btw: I’m customer since 3 months and I really enjoy using wakatime!
 
Thank you in advance! 

Best regards,
```

**Comment by dimateos** [comment]
Yep the URL sent to wakatime, even with `Entire URL` marked, is just the matched whitelist filter.
So e.g. I have `opengl` in there and would like to see the full urls not just `opengl` visited over and over.

> Maybe the `Only the domain` option could also work to cut the sent URL. However then I would need the whitelist filter to still match the full URL before cutting and sending it.
