### ISSUE TITLE
Ignore browsing websites in Language dashboard

### ISSUE THREAD

**Issue by szw0407** [wakatime/browser-wakatime#239]
Not quite sure how to do that:

Websites are not written in programing languages, so most Browsing activities had better not be included in the language dashboard, except those websites showing codes such as GitHub, GitLab, etc.

I hope these activities can be set as Hidden in custom rule settings about program languages.

**Comment by alanhamlett** [comment]
If you want to view the language pie chart without any language, click that language in the pie chart legend to hide it temporarily from the chart.

Otherwise, we don't support hiding any activity from dashboards.
