### ISSUE TITLE
WakaTime uses Header in Project Name

### ISSUE THREAD

**Issue by gmitch215** [wakatime/browser-wakatime#241]
Hello,
The WakaTime Firefox Plugin includes the header name (e.g. `#readme`) in the project, which can create project names such as `MyProject#readme`, which doesn't point to the correct name of the project.

<img alt="Screenshot 2023-11-17 at 9 37 34 PM" src="https://github.com/wakatime/browser-wakatime/assets/54124162/4388c645-1a1c-4c14-9117-40df3d264540">

**Comment by iam-rohid** [comment]
Fixed #258
