### ISSUE TITLE
Firefox display unknown host name

### ISSUE THREAD

**Issue by Freed-Wu** [wakatime/browser-wakatime#244]
Firefox display unknown host name. Is it a bug? Can chrome display host name correctly?

![Screenshot from 2023-11-28 02-29-59](https://github.com/wakatime/browser-wakatime/assets/32936898/08bbd9f0-ce42-47be-8c1e-645b03be49c2)

**Comment by guibranco** [comment]
You need to set this in the extension settings.

**Comment by Freed-Wu** [comment]
I see. It cannot detect hostname automatically?

**Comment by Freed-Wu** [comment]
If I set `Hostname = laptop` in my laptop, my desktop's extension will also use `Hostname = laptop`. Can it be set different?
