### ISSUE TITLE
3.0.22 -> 3.0.24 = no more tracking 

### ISSUE THREAD

**Issue by jmbarbier** [wakatime/browser-wakatime#280]
On both firefox and chrome, the migration from 3.0.22 to 3.0.24 disabled the tracking. No heartbeat is shown in heartbeat api, and the plugin status page is stuck with 3.0.22 from before the upgrade.

Diving into extension code, it seems that `this.db` in `WakaTimeCore.ts` is undefined when trying to send the heartbeats in `sendHeartbeats()` :

```ts
const heartbeats = (await this.db?.getAll(config.queueName, undefined, 50)) as
      | Heartbeat[]
      | undefined;
```

It seems that `createDB()` is not called. I just added a little check before this line to call it, and the extension worked well.

```ts
    if (!this.db) {
      await this.createDB();
    }
```

I also added this line to `putHeartbeatsBackInQueue` and `handleActivity` (where `this.db` is also used) to ensure that `this.db` is not undefined.

With this hack, the functionality seems to be restored.

**Comment by alanhamlett** [comment]
I've renamed the IndexedDB database and bumped the db version so it's re-created fresh in v4.0.4. Does that fix it?
