### ISSUE TITLE
The new version cannot be used after successful installation

### ISSUE THREAD

**Issue by Kimani8888** [wakatime/browser-wakatime#285]
![image](https://github.com/user-attachments/assets/54a6e485-3413-4989-9e2a-b65f9eca08fa)
![image](https://github.com/user-attachments/assets/0a1f7432-1284-4984-9ba5-8bb2f23f4646)

**Comment by alanhamlett** [comment]
Error message is `This extension may be corrupted`.

Does it work if you load the unpacked extension from `build/chrome` folder after running `npm i && npm run build`?
