### ISSUE TITLE
Extension is no longer tracking time

### ISSUE THREAD

**Issue by fromage9747** [wakatime/browser-wakatime#291]
Ever since the most recent update to the extension, it has stopped tracking time. I have tried removing it and configuring it all again, but the result is the same.

Are there any logs that I can look at to see why nothing is being logged?  It worked well for months.

**Comment by fromage9747** [comment]
Just had this error get spat out in my console from one of the sites its supposed to be tracking

![image](https://github.com/user-attachments/assets/3a419fc5-36da-4310-80da-250f559bd97f)

```
Uncaught (in promise) Error: Extension context invalidated.
    at wakatimeScript.js:1:371252
    at wakatimeScript.js:1:371211
```

**Comment by ouuan** [comment]
I see "Cross-Origin Request Blocked" in the logs. I believe that https://github.com/wakatime/browser-wakatime/commit/88cd9943074d468359de98c551c6f964b0469191 caused the issue. That commit removed `<all_urls>` from `permissions`. `<all_urls>` was valid in manifest v2, but is now moved to `host_permissions` in manifest v3. So it is invalid as said in the commit on Chrome, but not on Firefox, which is still using manifest v2. Now on Firefox, the extension does not have permission to send cross-origin requests to the WakaTime server.

However, adding back `<all_urls>` would pose potential security risks. It would be better to only declare permissions for the WakaTime server. But in order to support custom servers, it should request permissions during runtime when the user sets the API URL in the settings.

By the way, I think we can use manifest v3 for Firefox to be consistent with Chrome.

**Comment by ouuan** [comment]
> By the way, I think we can use manifest v3 for Firefox to be consistent with Chrome.

#161 was opened just 2 days after Firefox 109 with MV3 support was released. I guess that was the reason to keep using MV2 for Firefox. Now it makes sense to migrate to MV3 for Firefox.

**Comment by fromage9747** [comment]
@ouuan Is there any workaround to get this working for now? Surely I'm not the only one experiencing this issue?

**Comment by ouuan** [comment]
> @ouuan Is there any workaround to get this working for now? Surely I'm not the only one experiencing this issue?

First, I want to make sure whether you are using the official WakaTime server (<https://api.wakatime.com/>) and whether you are using Chrome or Firefox. According to your screenshot, it seems that you are using Chrome. However, based on my experiments, the CORS request failure only happens for Firefox and custom WakaTime servers.

For further troubleshooting:

- Check the "Site access: Allow this extension to read and change all your data on websites you visit" option on the extension details page.
- Do you always see the "Extension context invalidated" error? I only see this error when I reinstall the extension.
- Go to <chrome://inspect/#service-workers> and click "inspect" of `jnbbnacmeggbgdjgaoojpmhdlkkpblgi`. See the logs there.

**Comment by fromage9747** [comment]
@ouuan Thank you for getting back to me.

1. I am using https://api.wakatime.com/api/v1:

![image](https://github.com/user-attachments/assets/71cb48c1-ca88-4eb0-9d8f-c75eb9c8cb65)

2. I am using Google Chrome Version 130.0.6723.117 (Official Build) (64-bit)
3. Permissions
Read and change all your data on all websites

![image](https://github.com/user-attachments/assets/aca7df77-aeac-4681-b37e-d27c55749cd4)

4. "Extension context invalidated" It was something that I noticed shortly after logging this in GitHub and I had just reinstalled the extension as a last resort to try and get it working again.
5. If I click on just the service worker there is nothing, it is blank:

![image](https://github.com/user-attachments/assets/26b3e1e5-083a-4a88-91e9-2bafd16bddcf)

6. If I click on the other link under the service worker I get the below:

![image](https://github.com/user-attachments/assets/c62abd3b-19e3-4faf-ac28-1c4995dd2bb1)

Is there anything else I can look at to find the issue?

**Comment by ouuan** [comment]
> 3\. Permissions
>         Read and change all your data on all websites

What about the "Site Access" under "Permissions"? You can change the permissions there.

> 5\. If I click on just the service worker there is nothing, it is blank:

Also check the Network tab. Switch between tabs and go back to the service worker inspector to see if heartbeats are sent.

**Comment by fromage9747** [comment]
I have this:

![image](https://github.com/user-attachments/assets/51c90419-007e-4886-bb77-31a24b935767)

Can't find anything regarding Site Access under:
chrome://settings/content/siteDetails?site=chrome-extension://jnbbnacmeggbgdjgaoojpmhdlkkpblgi

Checking the network tab whilst flipping through a few sites I get the below:

![image](https://github.com/user-attachments/assets/1336771e-5723-4781-8e77-eb71cfb79555)

This is all being performed whilst using Chrome on Windows.  I thought I should give it a try using Chrome on Mac and its the same result.

I also tried using Chrome in Incognito mode with only the Wakatime extension enabled to remove any doubt of a conflicting extension, and it's the same outcome.

**Comment by ouuan** [comment]
Try clicking the extension icon. It should send requests to the WakaTime server to get and display the stats if working normally:

![image](https://github.com/user-attachments/assets/4f5ce55a-cd2c-4fdd-b590-6d10a9c5e9b3)

**Comment by fromage9747** [comment]
This always shows me my current time from when I work and track time through VSCode. And when I inspect the extension and then click on the icon I get the same network result as per my previous screenshot. 

When I reinstalled the extension, I also removed all of my included sites and tested with one site to track thinking that maybe one of my configured sites was causing an issue but even with just using once site, no tracking came through.  I tried with a few sites individually to get a good sample set of tests and none of them worked. 

Investigating a bit further, in the previous version when it did work.  When you added a new site you needed to add "@@" after the URL to track so that it came up in Wakatime under the category/name you wanted.  I just checked now, and the example provided no longer includes the "@@" perhaps this is my problem?

**Comment by fromage9747** [comment]
@ouuan Alright, it's tracking it now, but it's not logging it under the correct Project. Now that the "@@" functionality has been removed... I see that I have to add it under projects in order to get it to correctly log under the right project as it was logging it under a completely irrelevant project name. 

Looks like there was no issue with the extension, just configuration changes that I was unaware of after the most recent update.

I just double-checked the GitHub page and there isn't any reference to this configuration.

Anyway, glad its working now.

Thanks for the help.

**Comment by ouuan** [comment]
Fine, so we are encountering different issues. I think you can close this issue as this thread is now off-topic for my issue on Firefox.

**Comment by fromage9747** [comment]
Good luck!
