### ISSUE TITLE
Can't log in to Firefox WakaTime

### ISSUE THREAD

**Issue by yyizhak** [wakatime/browser-wakatime#294]
When I click Login in the extension, I am connected to Wakatime's logged in dashboard. 
However, I am still not logged in to the extension.
The API key has already been registered

![스크린샷 2024-11-15 085136](https://github.com/user-attachments/assets/b015b575-a484-45d5-95d9-0eed7ffd79b3)

I use windows 11 pro, firefox

**Comment by alanhamlett** [comment]
That UI is confusing, but the only thing necessary to login is your api key. Click `Options` instead of `Login` then make sure the API Key in the extension options matches the one for your account at https://wakatime.com/api-key. Does that fix it?

**Comment by yyizhak** [comment]
I already added my api key to the extension. However, it is displayed as an unknown editor on the dashboard. I want to know why Firefox is marked as an unknown editor.
![스크린샷 2024-11-15 172933](https://github.com/user-attachments/assets/cd2ded68-e2ff-4fdd-a881-b7fa51ea10f1)
