### ISSUE TITLE
Support for working offline by saving heartbeats locally

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/browser-wakatime#69]
Editor plugins support offline coding, and this extension should too. It could store heartbeats in [chrome.storage.local](https://developer.chrome.com/extensions/storage) with a capacity of [5MB](https://developer.chrome.com/extensions/storage#property-local). This would be local to the user's computer and not synced, since the [chrome.storage.sync](https://developer.chrome.com/extensions/storage#property-sync) limit of 100KB is too low.

**Comment by jvelezpo** [comment]
V3 already has`IndexedDB` integrated which supports storage capacity over 50MB which should be fine IMO for the extension/addon
[Here](https://github.com/wakatime/chrome-wakatime/blob/master/src/core/WakaTimeCore.ts#L28) is where it gets created.

This means when a user gets disconnected from the internet we store heartbeat in`IndexedDB`, once we detect the user is back online we send the heartbeats to Wakatime API
