### ISSUE TITLE
anyone have updated or working build instructions?

### ISSUE THREAD

**Issue by tamsky** [wakatime/browser-wakatime#70]
I tried taking some time today to build this project on my local machine but came up rather empty.

I took the steps from the README and put them into a `Dockerfile`:

https://github.com/tamsky/chrome-wakatime/commit/730bc7562fc66b39f83ce3bac3d624fdea6420c0

I expected that running the steps listed in the README would result in a working unpacked extension directory, that I can then point chrome at and the extension should work similar to the one in the chrome web store.

Currently `gulp` does not appear to even produce a required file: `//public/js/events.js` which is listed in `//manifest.json`
Chrome refuses to load the unpacked extension due to the missing manifest item.

If, out of curiousity, I uncomment a few currently commented out lines in the `//gulpfile.js`:
https://github.com/wakatime/chrome-wakatime/blob/6226b779225df99a5590ac4918e937e7823682c6/gulpfile.js#L51-L58

And rebuild using a similar `Dockerfile`... then `gulp` **does** produce the `//public/js/events.js` file, and the resulting extension **does** load unpacked in chrome.

But the extension doesn't function... it has show stopper errors like:
`Uncaught TypeError: WakaTimeCore is not a constructor` and
`Uncaught TypeError: Cannot read property 'ReactDebugCurrentFrame' of undefined`

Before going down any more debugging roads, can anyone tell me what I'm doing right, and what I'm doing wrong, and what I should be doing differently?

**Comment by Eeems** [comment]
See #75

**Comment by Eeems** [comment]
@tamsky This should be resolved now. Could you confirm?

**Comment by alanhamlett** [comment]
`npm i && npm run build`

or

`npm i && npm run watch`
