### ISSUE TITLE
README npm build instructions do not work

### ISSUE THREAD

**Issue by tamsky** [wakatime/browser-wakatime#74]
## ISSUE

@alanhamlett would it be possible for you to test, and update the build instructions for this project ?

Even when following the README build instructions, the required file `//public/js/events.js` listed in `//manifest.js` is never generated, resulting in an non-loadable extension.

My attempts (which have also included node:6, :8 , :10, etc) look like:
```
# docker run -it --name chrome-wakatime node:8 bash -x -c \
'
git clone https://github.com/wakatime/chrome-wakatime.git &&
  cd chrome-wakatime ;
  mkdir -p public/js ;
  npm install --unsafe-perm ;
  ./node_modules/bower/bin/bower --allow-root install ;
  ./node_modules/.bin/gulp ;
  find . -ls
'
```

**Comment by Eeems** [comment]
See #75

**Comment by Eeems** [comment]
@tamsky Could you confirm that this is now working as per #75 being merged?

**Comment by alanhamlett** [comment]
Fixed.
